# Generated by Django 5.0 on 2023-12-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('Name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobno', models.BigIntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('Adhaar', models.IntegerField()),
                ('user_pic', models.ImageField(blank=True, upload_to='user_img/')),
                ('user_docs', models.FileField(blank=True, upload_to='user_docs/')),
            ],
        ),
    ]
