# Generated by Django 5.0 on 2023-12-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_user_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Adhaar',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_category',
            field=models.CharField(max_length=30),
        ),
    ]
