# Generated by Django 5.0 on 2023-12-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_user_adhaar_alter_user_user_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobno', models.BigIntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('user_category', models.CharField(choices=[('3d', '3D PRINTING'), ('aqua', 'AQUA CULTURE'), ('water', 'WATER BODY MANAGEMENT')], default=(('3d', '3D PRINTING'), ('aqua', 'AQUA CULTURE'), ('water', 'WATER BODY MANAGEMENT')), max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
    ]
