# Generated by Django 5.0 on 2023-12-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_adminuser_superadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='token',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
    ]
